parameters:
    database_server:   www.geekcoding.net
    database_port:     27017
    database_name:     geekcoding
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            zh
    secret:            2793667
